In [1]:
import pandas as pd

df = pd.read_csv('/Users/tatiana/Desktop/АНДАН/olymp.csv')
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [2]:
df.head(10)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
5,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
6,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,Speed Skating Women's 500 metres,NaN
7,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
8,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,Speed Skating Women's 500 metres,NaN
9,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,"Speed Skating Women's 1,000 metres",NaN

In [4]:
df.tail(6)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
271110,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016 Summer,2016,Summer,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

In [5]:
df.dtypes

ID          int64
Name       object
Sex        object
Age       float64
Height    float64
Weight    float64
Team       object
NOC        object
Games      object
Year        int64
Season     object
City       object
Sport      object
Event      object
Medal      object
dtype: object

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      271116 non-null  int64
 1   Name    271116 non-null  object
 2   Sex     271116 non-null  object
 3   Age     261642 non-null  float64
 4   Height  210945 non-null  float64
 5   Weight  208241 non-null  float64
 6   Team    271116 non-null  object
 7   NOC     271116 non-null  object
 8   Games   271116 non-null  object
 9   Year    271116 non-null  int64
 10  Season  271116 non-null  object
 11  City    271116 non-null  object
 12  Sport   271116 non-null  object
 13  Event   271116 non-null  object
 14  Medal   39783 non-null   object
dtypes: float64(3), int64(2), object(10)
memory usage: 31.0+ MB

In [7]:
df.shape

(271116, 15)

In [9]:
df #DataFrame

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

In [8]:
df['City'] #Series object

0              Barcelona
1                 London
2              Antwerpen
3                  Paris
4                Calgary
               ...
271111         Innsbruck
271112             Sochi
271113             Sochi
271114            Nagano
271115    Salt Lake City
Name: City, Length: 271116, dtype: object

In [10]:
df[['Sport', 'Season', 'Team']]

                Sport  Season            Team
0          Basketball  Summer           China
1                Judo  Summer           China
2            Football  Summer         Denmark
3          Tug-Of-War  Summer  Denmark/Sweden
4       Speed Skating  Winter     Netherlands
...               ...     ...             ...
271111           Luge  Winter        Poland-1
271112    Ski Jumping  Winter          Poland
271113    Ski Jumping  Winter          Poland
271114      Bobsleigh  Winter          Poland
271115      Bobsleigh  Winter          Poland

[271116 rows x 3 columns]

In [11]:
df.loc[666]

ID                                386
Name                  Alexandre Abeid
Sex                                 M
Age                              26.0
Height                          194.0
Weight                           92.0
Team                           Brazil
NOC                               BRA
Games                     1976 Summer
Year                             1976
Season                         Summer
City                         Montreal
Sport                      Volleyball
Event     Volleyball Men's Volleyball
Medal                             NaN
Name: 666, dtype: object

In [21]:
df[df['Year'] == 1992].sort_values('Age')

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
73461,37333,Carlos Bienvenido Front Barrera,M,11.0,NaN,NaN,Spain,ESP,1992 Summer,1992,Summer,Barcelona,Rowing,Rowing Men's Coxed Eights,NaN
120234,60854,Judit Kiss,F,12.0,171.0,57.0,Hungary,HUN,1992 Summer,1992,Summer,Barcelona,Swimming,Swimming Women's 800 metres Freestyle,NaN
120233,60854,Judit Kiss,F,12.0,171.0,57.0,Hungary,HUN,1992 Summer,1992,Summer,Barcelona,Swimming,Swimming Women's 400 metres Freestyle,NaN
80831,41040,Gina Elena Gogean (-Groza),F,13.0,150.0,40.0,Romania,ROU,1992 Summer,1992,Summer,Barcelona,Gymnastics,Gymnastics Women's Balance Beam,NaN
265499,132855,"Wei Ling ""Joscelin"" Yeo",F,13.0,165.0,56.0,Singapore,SGP,1992 Summer,1992,Summer,Barcelona,Swimming,Swimming Women's 200 metres Individual Medley,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225906,113518,Oumou Sow,F,NaN,NaN,NaN,Guinea,GUI,1992 Summer,1992,Summer,Barcelona,Athletics,Athletics Women's 200 metres,NaN
233224,116990,Oleg Gennadyevich Sveshnikov,M,NaN,NaN,NaN,Unified Team,EUN,1992 Summer,1992,Summer,Barcelona,Rowing,Rowing Men's Coxed Eights,NaN
235767,118212,Idrissou Souaibo Tamimou,M,NaN,175.0,70.0,Benin,BEN,1992 Summer,1992,Summer,Barcelona,Athletics,Athletics Men's 800 metres,NaN
235768,118212,Idrissou Souaibo Tamimou,M,NaN,175.0,70.0,Benin,BEN,1992 Summer,1992,Summer,Barcelona,Athletics,"Athletics Men's 1,500 metres",NaN
238015,119360,Daniel Tesfaye,M,NaN,173.0,65.0,Ethiopia,ETH,1992 Summer,1992,Summer,Barcelona,Cycling,Cycling Men's 100 kilometres Team Time Trial,NaN

In [25]:
df[df['Year'] == 2012].drop_duplicates('ID').shape[0]

10517

In [27]:
df[(df['Sex'] == 'M') & (df['Sport'] == 'Basketball') & (df['Year'] == 2012)].shape[0]

144

In [28]:
round(144/10517, 2)

0.01

In [32]:
sorted(df[df['Sport'] == 'Curling']['Year'].unique())

[1924, 1998, 2002, 2006, 2010, 2014]

In [34]:
df[df['Sex'] == 'F'].sort_values('Year')

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
71787,36534,Madeleine Fournier-Sarlovze (La Perche-),F,26.0,NaN,NaN,France,FRA,1900 Summer,1900,Summer,Paris,Golf,Golf Women's Individual,NaN
44448,22925,Charlotte Reinagle Cooper (-Sterry),F,29.0,NaN,NaN,Great Britain,GBR,1900 Summer,1900,Summer,Paris,Tennis,Tennis Women's Singles,Gold
85934,43575,Elvira Guerra,F,NaN,NaN,NaN,Italy,ITA,1900 Summer,1900,Summer,Paris,Equestrianism,Equestrianism Mixed Hacks And Hunter Combined,NaN
79507,40381,"Catherine Marie Blanche ""Katie"" Gillou (-Fenwick)",F,13.0,NaN,NaN,France,FRA,1900 Summer,1900,Summer,Paris,Tennis,Tennis Mixed Doubles,NaN
51669,26559,Hlne de Pourtals (Barbey-),F,32.0,NaN,NaN,Lerina,SUI,1900 Summer,1900,Summer,Paris,Sailing,Sailing Mixed 1-2 Ton,Silver
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128588,64740,Susan Kuijken (-Krumins),F,30.0,172.0,54.0,Netherlands,NED,2016 Summer,2016,Summer,Rio de Janeiro,Athletics,"Athletics Women's 10,000 metres",NaN
128652,64768,Tatyana Aleksandrovna Kukhta,F,26.0,185.0,77.0,Belarus,BLR,2016 Summer,2016,Summer,Rio de Janeiro,Rowing,Rowing Women's Double Sculls,NaN
128736,64803,Jasmin Klbs,F,24.0,178.0,127.0,Germany,GER,2016 Summer,2016,Summer,Rio de Janeiro,Judo,Judo Women's Heavyweight,NaN
128850,64856,Leonie Kullmann,F,16.0,175.0,62.0,Germany,GER,2016 Summer,2016,Summer,Rio de Janeiro,Swimming,Swimming Women's 4 x 200 metres Freestyle Relay,NaN
271110,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016 Summer,2016,Summer,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN

In [38]:
df[(df['Year'] == 1900) & (df['Sex'] == 'F')].drop_duplicates('ID').shape[0]

23

In [41]:
df[(df['Year'] == 1900) & (df['Sex'] == 'F')]['Sport'].unique()

array(['Golf', 'Tennis', 'Sailing', 'Croquet', 'Equestrianism'],
      dtype=object)

In [43]:
df[df['Name'] == 'Usain St. Leo Bolt'].sort_values('Year')

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
24876,13029,Usain St. Leo Bolt,M,17.0,196.0,95.0,Jamaica,JAM,2004 Summer,2004,Summer,Athina,Athletics,Athletics Men's 200 metres,NaN
24877,13029,Usain St. Leo Bolt,M,21.0,196.0,95.0,Jamaica,JAM,2008 Summer,2008,Summer,Beijing,Athletics,Athletics Men's 100 metres,Gold
24878,13029,Usain St. Leo Bolt,M,21.0,196.0,95.0,Jamaica,JAM,2008 Summer,2008,Summer,Beijing,Athletics,Athletics Men's 200 metres,Gold
24879,13029,Usain St. Leo Bolt,M,21.0,196.0,95.0,Jamaica,JAM,2008 Summer,2008,Summer,Beijing,Athletics,Athletics Men's 4 x 100 metres Relay,NaN
24880,13029,Usain St. Leo Bolt,M,25.0,196.0,95.0,Jamaica,JAM,2012 Summer,2012,Summer,London,Athletics,Athletics Men's 100 metres,Gold
24881,13029,Usain St. Leo Bolt,M,25.0,196.0,95.0,Jamaica,JAM,2012 Summer,2012,Summer,London,Athletics,Athletics Men's 200 metres,Gold
24882,13029,Usain St. Leo Bolt,M,25.0,196.0,95.0,Jamaica,JAM,2012 Summer,2012,Summer,London,Athletics,Athletics Men's 4 x 100 metres Relay,Gold
24883,13029,Usain St. Leo Bolt,M,29.0,196.0,95.0,Jamaica,JAM,2016 Summer,2016,Summer,Rio de Janeiro,Athletics,Athletics Men's 100 metres,Gold
24884,13029,Usain St. Leo Bolt,M,29.0,196.0,95.0,Jamaica,JAM,2016 Summer,2016,Summer,Rio de Janeiro,Athletics,Athletics Men's 200 metres,Gold
24885,13029,Usain St. Leo Bolt,M,29.0,196.0,95.0,Jamaica,JAM,2016 Summer,2016,Summer,Rio de Janeiro,Athletics,Athletics Men's 4 x 100 metres Relay,Gold

In [44]:
def age_cat(x):
    if x<18:
        return "меньше 18"
    elif x<30:
        return "от 18 до 30"
    elif x>=30:
        return "30 и больше"
    else:
        return x

In [45]:
df['Age_category'] = df['Age'].apply(age_cat)
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,Age_category
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,от 18 до 30
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,от 18 до 30
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,от 18 до 30
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,30 и больше
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN,от 18 до 30

In [48]:
df[df['Age_category'] == '30 и больше'].drop_duplicates('ID').shape[0]

29525

In [49]:
df[(df['Age_category'] == '30 и больше') & (df['Medal'] == 'Gold')].drop_duplicates('ID').shape[0]

2288

In [52]:
round(2288/29525*100, 2)

7.75

In [53]:
df['BMI'] = df['Weight']/(df['Height']/100)**2
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,Age_category,BMI
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,от 18 до 30,24.691358
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,от 18 до 30,20.761246
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,от 18 до 30,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,30 и больше,NaN
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN,от 18 до 30,23.959094

In [56]:
round(df['BMI'].max()-df['BMI'].min(), 2)

55.54

In [57]:
NA_cities = ['St. Louis', 'Los Angeles', 'Lake Placid', 'Squaw Valley', 'Mexico City', 'Montreal', 'Calgary', 'Atlanta', 
             'Salt Lake City', 'Vancouver']
df['NA_olymp'] = df['City'].apply(lambda x: x in NA_cities)
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,Age_category,BMI,NA_olymp
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,от 18 до 30,24.691358,False
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,от 18 до 30,20.761246,False
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,от 18 до 30,NaN,False
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,30 и больше,NaN,False
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN,от 18 до 30,23.959094,True

In [61]:
df[(df['Season'] == 'Winter') & (df['NA_olymp'] == True)].sort_values('Year', ascending = False)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,Age_category,BMI,NA_olymp
136032,68439,Lari Lehtonen,M,22.0,176.0,72.0,Finland,FIN,2010 Winter,2010,Winter,Vancouver,Cross Country Skiing,Cross Country Skiing Men's 30 km Skiathlon,NaN,от 18 до 30,23.243802,True
182628,91797,Anja Sofia Tess Prson,F,28.0,170.0,81.0,Sweden,SWE,2010 Winter,2010,Winter,Vancouver,Alpine Skiing,Alpine Skiing Women's Super G,NaN,от 18 до 30,28.027682,True
182630,91797,Anja Sofia Tess Prson,F,28.0,170.0,81.0,Sweden,SWE,2010 Winter,2010,Winter,Vancouver,Alpine Skiing,Alpine Skiing Women's Slalom,NaN,от 18 до 30,28.027682,True
182631,91797,Anja Sofia Tess Prson,F,28.0,170.0,81.0,Sweden,SWE,2010 Winter,2010,Winter,Vancouver,Alpine Skiing,Alpine Skiing Women's Combined,Bronze,от 18 до 30,28.027682,True
85007,43139,Stefan Groothuis,M,28.0,181.0,78.0,Netherlands,NED,2010 Winter,2010,Winter,Vancouver,Speed Skating,"Speed Skating Men's 1,500 metres",NaN,от 18 до 30,23.808797,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227129,114130,Frank Stack,M,26.0,NaN,NaN,Canada,CAN,1932 Winter,1932,Winter,Lake Placid,Speed Skating,"Speed Skating Men's 5,000 metres",NaN,от 18 до 30,NaN,True
227128,114130,Frank Stack,M,26.0,NaN,NaN,Canada,CAN,1932 Winter,1932,Winter,Lake Placid,Speed Skating,"Speed Skating Men's 1,500 metres",NaN,от 18 до 30,NaN,True
227127,114130,Frank Stack,M,26.0,NaN,NaN,Canada,CAN,1932 Winter,1932,Winter,Lake Placid,Speed Skating,Speed Skating Men's 500 metres,NaN,от 18 до 30,NaN,True
103289,52266,Alexandru Ionescu,M,28.0,170.0,NaN,Romania,ROU,1932 Winter,1932,Winter,Lake Placid,Bobsleigh,Bobsleigh Men's Four,NaN,от 18 до 30,NaN,True
139517,70068,Karl Eskil Ingvar Lindberg,M,20.0,175.0,NaN,Sweden,SWE,1932 Winter,1932,Winter,Lake Placid,Speed Skating,"Speed Skating Men's 10,000 metres",NaN,от 18 до 30,NaN,True

In [58]:
df.dtypes

ID                int64
Name             object
Sex              object
Age             float64
Height          float64
Weight          float64
Team             object
NOC              object
Games            object
Year              int64
Season           object
City             object
Sport            object
Event            object
Medal            object
Age_category     object
BMI             float64
NA_olymp           bool
dtype: object